### PR TITLE
Fix simple value plugin constuctor

### LINKED ISSUE #986: 1.0.17 버전에서 SimpleValueJqwikPlugin 사용시 Set<Integer> 의 임의값이 생성되지 않습니다.
## Describe the bug
SimpleValueJqwikPlugin 사용시 Set<Integer> 유형에 2개이상 엘리먼트에 할당되도록 했을시, sample 객체 생성이 완료되지 못하고 무한루프 하고 있습니다.

## Your environment
* version of Fixture Monkey : 1.0.17 + SimpleValueJqwikPlugin
* version of Java/Kotlin : 1.8, 11, 17

## Steps to reproduce
```java
public class TestObject {

	private Set<Integer> integers;

	public Collection<Integer> getIntegers() {
		return integers;
	}
}
```

```java
public class SampleCreatingFailureTest {

	@Property(tries = 10)
	void test() {
		// given
		FixtureMonkey sut = FixtureMonkey.builder()
			.objectIntrospector(FieldReflectionArbitraryIntrospector.INSTANCE)
			.plugin(new SimpleValueJqwikPlugin())
			.build();

		// when  - sample 객체가 생성되지 않고 무한루프 합니다.
		TestObject actual = sut.giveMeBuilder(TestObject.class)
			.size("integers", 2)
			.sample();

		// then
		then(actual).isNotNull();
		then(actual.getIntegers()).hasSize(2);
	}
}
```

## Expected behaviour
`Set<Integer> integers` 필드에 2개의 엘리먼트에 임의 값들이 할당되어야 합니다.

## Actual behaviour
하지만 무한루프와 함께 할당이 되지 않고 객체생성이 되지 않아 .sample() 다음 라인으로 진행되지 않습니다.

아래 조치중 하나를 하면 정상 동작하고 있습니다.
1. 엘리먼트를 1개 이하로 생성되도록 변경 (예: `.size("integers", 1)` 로 변경)
2. integers 필드 유형을 Set에서 List로 변경
3. `Set<Integer>` 의 제네릭을 Number가 아닌 유형으로 변경. (예: `Set<String>`)
4. SimpleValueJqwikPlugin 플러그인을 제거

### PR DESCRIPTION
**Pull request by Ting-Kim**
## Summary
*Describe what feature is implemented by this PR.*
*If there is a related issue, write the issue number and link*

Resolves #986 

## (Optional): Description
*Describe your changes in detail*

Fixed a problem with the order of parameters injected when creating an instance of `SimpleValueJqwikPlugin` in the `accept()` method within the `SimpleValueJqwikPlugin` class.

## How Has This Been Tested?
*Please describe the tests that you ran to verify your changes.*

to verify the scenario that was reproduced in the #986 issue.

### CODE REVIEW

File: fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/plugin/SimpleValueJqwikPlugin.java [hunk 1]
```diff
@@ -141,10 +141,10 @@ public void accept(FixtureMonkeyOptionsBuilder optionsBuilder) {
 							new SimpleJavaConstraintGenerator(
 								this.minStringLength,
 								this.maxStringLength,
-								this.positiveMinNumberValue,
-								this.positiveMaxNumberValue,
 								this.negativeMinNumberValue,
 								this.negativeMaxNumberValue,
+								this.positiveMinNumberValue,
+								this.positiveMaxNumberValue,
```
Comment (seongahjo) [inline fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/plugin/SimpleValueJqwikPlugin.java:147]: For keeping consistency with `JavaDecimalConstraint`, `JavaIntegerConstraint` , it is better to be positive first and then negative.

Could you fix the order of the fields in `SimpleJavaConstraintGenerator` ?

Comment (Ting-Kim) [reply fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/plugin/SimpleValueJqwikPlugin.java:147]: Sure. I'm going to try that, and give you notie :)

**Comment by Ting-Kim** [comment]
@seongahjo 
I've reflected, so please check. ☺️

**Review by seongahjo — APPROVED** [review]

**Comment by seongahjo** [comment]
It's perfect. Thank you for your contributing!

**Comment by Ting-Kim** [comment]
> It's perfect. Thank you for your contributing!

Thanks for the help.
I would be very happy if I could continue to contribute ☺️

Plus, I have a question.
It would be nice if validation logic was in the creator to prevent this issue from happening again, do you have any related conventions or anything?

**Comment by seongahjo** [comment]
@Ting-Kim 
> Thanks for the help.
I would be very happy if I could continue to contribute 

Of course, we'd love to hear from you!

> It would be nice if validation logic was in the creator to prevent this issue from happening again, do you have any related conventions or anything?

I think it is better to validate `SimpleJavaConstraintGenerator` in its constructor, since `SimpleJavaConstraintGenerator` is not inherited unless really needed.

**Comment by Ting-Kim** [comment]
@seongahjo 
I see. Thank you very much for your answer. :)
